DROP TABLE IF EXISTS CAR;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(12),
    FIRST_NAME VARCHAR(32),
    LAST_NAME VARCHAR(64),
    USER_ROLE VARCHAR(6)
);
CREATE TABLE CAR
(
    CAR_ID INT PRIMARY KEY AUTO_INCREMENT,
    MAKE VARCHAR(20),
    MODEL VARCHAR(20),
    COLOUR VARCHAR(20),
    YEAR INT,
    OWNER_ID INT,
    FOREIGN KEY (OWNER_ID) REFERENCES USER(USER_ID)
);